###
# #%L
# aiSSEMBLE::Open Inference Protocol Use Cases::FastAPI, gRPC, and Kserve Inference
# %%
# Copyright (C) 2024 Booz Allen Hamilton Inc.
# %%
# This software package is licensed under the Booz Allen Public License. All Rights Reserved.
# #L%
###
# Disable auth for this example
auth_enabled=false
auth_secret=
pdp_url=http://localhost:8080/pdp

