apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: kserve-model
spec:
  predictor:
    containers:
      - name: "oip-use-case"
        image: oip-use-case:1.0.0-SNAPSHOT
        env:
          - name: KSERVE_HTTP_PORT
            value: "8080"